---
title: "Before the Workshop"
---


Again, because this is a four hour workshop, we ask that you come prepared with
a laptop that has the most recent versions of [R] and [RStudio] installed, and
our [workshop materials] downloaded to your Desktop. **We cannot provide service
for installation the day of the workshop.**

Installation
------------

Even if you already have [R] installed on your system, you really should make
sure its up to date. This ensures that there are no problems due to outdated
software. For more details about installing [R], [RStudio], and keeping
everything up to date, UBC's [STAT545] page is an excellent resource.

 - [R]
 - [RStudio]
 - [Workshop Materials] (zip file; unzip to Desktop)
 - (Once you've installed R), install packages "[dplyr]", "[ggplot2]", "[plotrix]", "[RColorBrewer]", and "[ggpubr]"

Verification
------------

Once you have installed [R], we should verify that you have the correct version.

 1. Open R (or RStudio) on your computer
 2. Enter the following in the R console after the `>`    
        
        R.version.string == "R version 3.6.2 (2019-12-12)"
        
 3. Make sure the result is **`[1] TRUE`**    
    (If the result is `[1] FALSE`, please quit R and try the installation again)
 
 
Workshop Materials
------------------

Our [workshop materials] is a zip file that contains a folder called 
`APS_IntroR_2020-master/` with the folowing structure:

```
.
├── APS_IntroR_2020.Rproj
├── LICENSE
├── Makefile
├── Part1-Introduction.R
├── Part2-Analysis.R
├── Part3-Visualization.R
├── README.md
├── data/
│   ├── fungicide_dat.csv
│   └── README.md
└── docs/
    └── ...
```

We are providing the R scripts for the workshop, so that you can easily 
execute the code in these scripts to follow along.

Installing Packages
-------------------

To install [dplyr], [ggplot2], [plotrix], [RColorBrewer], and [ggpubr] to your system, open R and type:

```{r, eval = FALSE}
install.packages(c("dplyr", "ggplot2", "plotrix", "RColorBrewer", "ggpubr"), 
                 repos = "https://cloud.r-project.org/")
```

Presentation Files
-------------------

The presentations that were used during Part 1 and Part 2 of the workshop can be downloaded from

 1. [Slides_IntroR_2020_Webinar_Part1]
 2. [Slides_IntroR_2020_Webinar_Part2]

[stat545]: http://stat545.com/block000_r-rstudio-install.html
[R]: https://cloud.r-project.org/
[RStudio]: https://www.rstudio.com/products/rstudio/download/
[Workshop Materials]: https://github.com/everhartlab/APS_IntroR_2020/archive/master.zip
[dplyr]: https://dplyr.tidyverse.org
[ggplot2]: https://ggplot2.tidyverse.org
[plotrix]: https://crantastic.org/packages/plotrix
[RColorBrewer]: https://www.datanovia.com/en/blog/the-a-z-of-rcolorbrewer-palette/
[ggpubr]: https://rpkgs.datanovia.com/ggpubr/
[Slides_IntroR_2020_Webinar_Part1]: https://github.com/everhartlab/APS_IntroR_2020/blob/master/docs/slides/IntroR_2020_Webinar_Part1_2-19-2020.pdf
[Slides_IntroR_2020_Webinar_Part2]: https://github.com/everhartlab/APS_IntroR_2020/blob/master/docs/slides/IntroR_2020_Webinar_Part2_2-26-2020.pdf
